//
// Created by cc on 05.11.23.
//

#ifndef QT1SIMPLETEXTEDITORDEMO_FILTERCREATOR_H
#define QT1SIMPLETEXTEDITORDEMO_FILTERCREATOR_H


class FilterCreator {

};


#endif //QT1SIMPLETEXTEDITORDEMO_FILTERCREATOR_H
